name: My First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List and Read File
              run: |
                echo "My First Github Action Workflow"
                ls -lrta
                cat README.md

            # - name: Generate ASCII Artwork
            #   run: cowsay -f dragon "Run for cover, I'm a DRAGON!!!!RAWR" >> dragon.txt

            - uses: mscoutermarsh/ascii-art-action@master
              with:
                text: "Run for cover, I'm a DRAGON!!!!RAWR"

            # - name: List Files
            #   run: ls -la

            # - name: Read file
            #   run: cat README.md